### ISSUE TITLE
trying to use "25fdbed983314f8b23c361180e861da73f8c24f4a194ecd6bac01fc8bb2d483a.so" receives this error

### ISSUE THREAD

**Issue by Shaistrong** [FizzleDorf/AIT#16]
`Found 3 modules for windows xl sm80 1 1024 unet
Using f64294f9bae73c4f742a4f61e8567460d1abefb461c792f69e8922c74331cd27
100%|██████████████████████████████████████████████████████████████████████████████████| 67/67 [00:08<00:00,  9.82it/s]
Found 3 modules for windows v1 sm80 1 1024 unet
Using 25fdbed983314f8b23c361180e861da73f8c24f4a194ecd6bac01fc8bb2d483a
[08:15:48]: NVIDIA GeForce RTX 4070 Ti
[08:15:48]: AITemplate modules compiled by hlky
[08:15:48]: Error: SetConstant did not receive correct number of bytes for unbound constant time_embedding_linear_1_weight: expected 819200 but got 1179648. Check that the provided tensor's shape is correct.
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI\execution.py", line 144, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI\execution.py", line 74, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI\execution.py", line 67, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI\nodes.py", line 1165, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI\custom_nodes\AIT\AITemplate\AITemplate.py", line 170, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI\custom_nodes\AIT\AITemplate\AITemplate.py", line 269, in sample
    AITemplate.unet[module['sha256']] = AITemplate.loader.apply_unet(
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI\custom_nodes\AIT\AITemplate\ait\load.py", line 215, in apply_unet
    return self.apply(aitemplate_module, ait_params)
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI\custom_nodes\AIT\AITemplate\ait\load.py", line 194, in apply
    aitemplate_module.set_many_constants_with_tensors(ait_params)
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI\custom_nodes\AIT\AITemplate\ait\module\model.py", line 839, in set_many_constants_with_tensors
    self.set_many_constants(ait_tensors)
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI\custom_nodes\AIT\AITemplate\ait\module\model.py", line 790, in set_many_constants
    self.DLL.AITemplateModelContainerSetManyConstants(
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI\custom_nodes\AIT\AITemplate\ait\module\model.py", line 211, in _wrapped_func
    raise RuntimeError(f"Error in function: {method.__name__}")
RuntimeError: Error in function: AITemplateModelContainerSetManyConstants

Prompt executed in 25.88 seconds`

**Comment by Shaistrong** [comment]
this happens when the refiner stage starts

**Comment by FizzleDorf** [comment]
I can recreate this error but I'm out of time for tonight to deal with it. I also opened a new repo with just the newly made modules. I put the link in the README.txt. The other modules work fine for you correct?

**Comment by Shaistrong** [comment]
> I can recreate this error but I'm out of time for tonight to deal with it. I also opened a new repo with just the newly made modules. I put the link in the README.txt. Do the other modules work fine for you?

yes, it's just the refiner part.

**Comment by hlky** [comment]
Please refer to the many previous comments that explain refiner is not currently supported. Please wait patiently for refiner support. If you do not wish to wait, you are free to fix it yourself.

**Comment by Shaistrong** [comment]
> Please refer to the many previous comments that explain refiner is not currently supported. Please wait patiently for refiner support. If you do not wish to wait, you are free to fix it yourself.

yeah, I figured it out. the node sees the refiner as a V1 model for some reason. we need to add a flag to modules.jason for it

**Comment by FizzleDorf** [comment]
the refiner code has been updated in the [sdxl branch](https://github.com/FizzleDorf/AIT/tree/sdxl). Please checkout and confirm the changes are working if possible and report if anything is still broken. The faster we know everything is testing properly the faster I can merge the branch without problems moving forward.

**Comment by Shaistrong** [comment]
> the refiner code has been updated in the [sdxl branch](https://github.com/FizzleDorf/AIT/tree/sdxl). Please checkout and confirm the changes are working if possible and report if anything is still broken. The faster we know everything is testing properly the faster I can merge the branch without problems moving forward.

alright. it still sees the refiner as a V1 model for some reason. changing the inference code wasn't needed. however, I still needed to manually place the .SO file for SDXL

**Comment by hlky** [comment]
You're not using CLIPTextEncodeSDXLRefiner

**Comment by Shaistrong** [comment]
> You're not using CLIPTextEncodeSDXLRefiner

what's that? another node?

**Comment by Shaistrong** [comment]
> You're not using CLIPTextEncodeSDXLRefiner

okay, now it does this: 
`Found 3 modules for windows xl sm80 1 1024 unet
Using f64294f9bae73c4f742a4f61e8567460d1abefb461c792f69e8922c74331cd27
100%|██████████████████████████████████████████████████████████████████████████████████| 67/67 [00:08<00:00,  10.97it/s]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI\nodes.py", line 1206, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI\custom_nodes\AIT-sdxl\AITemplate\AITemplate.py", line 171, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI\custom_nodes\AIT-sdxl\AITemplate\AITemplate.py", line 250, in sample
    module = AITemplate.loader.filter_modules(AIT_OS, sd, AIT_CUDA, batch_size, resolution, model_type)[0]
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI\custom_nodes\AIT-sdxl\AITemplate\ait\load.py", line 75, in filter_modules
    raise ValueError(f"No modules found for {operating_system} {sd} {cuda} {batch_size} {resolution} {model_type}")
ValueError: No modules found for windows xlr sm80 1 1024 unet`

**Comment by hlky** [comment]
That is to be expected because the refiner modules have not been added to modules.json yet. The file will be updated soon, I am currently preparing Linux modules to share with FizzleDorf and updating the file. Alternatively you can add an entry manually.

**Comment by Shaistrong** [comment]
> That is to be expected because the refiner modules have not been added to modules.json yet. The file will be updated soon, I am currently preparing Linux modules to share with FizzleDorf and updating the file. Alternatively you can add an entry manually.

I see. also still had to manually place the .SO files for XL base, it still makes a 0 byte file by default and needs to be replaced

**Comment by hlky** [comment]
Yes, that is because the modules.json hasn't been updated yet. When everything is complete the sdxl branch will be merged.

**Comment by Shaistrong** [comment]
> Yes, that is because the modules.json hasn't been updated yet. When everything is complete the sdxl branch will be merged.

alright, checked out the new changes to modules .JSON, gives a different error:
`100%|██████████████████████████████████████████████████████████████████████████████████| 67/67 [00:08<00:00,  12.30it/s]
Found 3 modules for windows xlr sm80 1 1024 unet
Using f4934a1df4101eb689d3c845dd1f25059cacd6f1f79afbe023c412efd358fbbc
Error: SetConstant did not receive correct number of bytes for unbound constant arange: expected 384 but got 320. Check that the provided tensor's shape is correct.
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI\nodes.py", line 1206, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI\custom_nodes\AIT-sdxl\AITemplate\AITemplate.py", line 171, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI\custom_nodes\AIT-sdxl\AITemplate\AITemplate.py", line 274, in sample
    AITemplate.unet[module['sha256']] = AITemplate.loader.apply_unet(
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI\custom_nodes\AIT-sdxl\AITemplate\ait\load.py", line 217, in apply_unet
    return self.apply(aitemplate_module, ait_params)
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI\custom_nodes\AIT-sdxl\AITemplate\ait\load.py", line 196, in apply
    aitemplate_module.set_many_constants_with_tensors(ait_params)
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI\custom_nodes\AIT-sdxl\AITemplate\ait\module\model.py", line 840, in set_many_constants_with_tensors
    self.set_many_constants(ait_tensors)
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI\custom_nodes\AIT-sdxl\AITemplate\ait\module\model.py", line 791, in set_many_constants
    self.DLL.AITemplateModelContainerSetManyConstants(
  File "C:\Users\joker\OneDrive\Desktop\A.I\ComfyUI\custom_nodes\AIT-sdxl\AITemplate\ait\module\model.py", line 212, in _wrapped_func
    raise RuntimeError(f"Error in function: {method.__name__}")
RuntimeError: Error in function: AITemplateModelContainerSetManyConstants

Prompt executed in 25.62 seconds`

**Comment by hlky** [comment]
> expected 384 but got 320.
You're not using the refiner model.

**Comment by Shaistrong** [comment]
> > expected 384 but got 320.
> 
> You're not using the refiner model.

am I supposed to use "sd_xl_refiner_1.0_0.9vae"?

**Comment by Shaistrong** [comment]
okay, just pulled the new changes to the SDXL branch, it works!
