### ISSUE TITLE
Trying to use SDXL AiTemplate on linux but ending up with this error

### ISSUE THREAD

**Issue by CyberTimon** [FizzleDorf/AIT#20]
Hello! I try to use this AiTemplate plugin on linux, but I receive this error when using it on linux ubuntu 22.04:

```
Found 3 modules for linux xl sm80 1 1024 unet
Using b5caabe98aeb69bada9d1566c897aed66a84d4fb21f31482160d7ef9987f04fd
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/home/cybertimon/Repositories/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/cybertimon/Repositories/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/cybertimon/Repositories/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/cybertimon/Repositories/ComfyUI/nodes.py", line 1206, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "/home/cybertimon/Repositories/ComfyUI/custom_nodes/AIT/AITemplate/AITemplate.py", line 171, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/home/cybertimon/Repositories/ComfyUI/custom_nodes/AIT/AITemplate/AITemplate.py", line 259, in sample
    AITemplate.unet[module['sha256']] = AITemplate.loader.load_module(module['sha256'], module['url'])
  File "/home/cybertimon/Repositories/ComfyUI/custom_nodes/AIT/AITemplate/ait/load.py", line 69, in load_module
    self.download_module(sha256, url)
  File "/home/cybertimon/Repositories/ComfyUI/custom_nodes/AIT/AITemplate/ait/load.py", line 56, in download_module
    g.write(f.read())
  File "/usr/lib/python3.10/lzma.py", line 200, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.10/_compression.py", line 118, in readall
    while data := self.read(sys.maxsize):
  File "/usr/lib/python3.10/_compression.py", line 103, in read
    data = self._decompressor.decompress(rawblock, size)
_lzma.LZMAError: Input format not supported by decoder
```

I'm on the sdxl branch.
Thanks for help!

**Comment by CyberTimon** [comment]
I'm closing this as I saw that you guys are working on support! Thank you soo much for AiTemplate support.
