### ISSUE TITLE
module 'comfy.sd' has no attribute 'ModelPatcher'

### ISSUE THREAD

**Issue by Rkkss** [FizzleDorf/AIT#48]
Was reported here https://github.com/comfyanonymous/ComfyUI/issues/1426

```
!!! Exception during processing !!!
Traceback (most recent call last):
File "K:\AI ART UNIVERSE\COMFY-UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "K:\AI ART UNIVERSE\COMFY-UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "K:\AI ART UNIVERSE\COMFY-UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "K:\AI ART UNIVERSE\COMFY-UI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 577, in load_controlnet
controlnet = comfy.controlnet.load_controlnet(controlnet_path)
File "K:\AI ART UNIVERSE\COMFY-UI\ComfyUI_windows_portable\ComfyUI\comfy\controlnet.py", line 394, in load_controlnet
control = ControlNet(control_model, global_average_pooling=global_average_pooling)
File "K:\AI ART UNIVERSE\COMFY-UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\AIT\AITemplate\AITemplate.py", line 347, in init
self.control_model_wrapped = comfy.sd.ModelPatcher(self.control_model, load_device=comfy.model_management.get_torch_device(), offload_device=comfy.model_management.unet_offload_device())
AttributeError: module 'comfy.sd' has no attribute 'ModelPatcher'
```

**Comment by FizzleDorf** [comment]
resolved in f74366c
