### ISSUE TITLE
Unable to compile modules after update

### ISSUE THREAD

**Issue by M1kep** [FizzleDorf/AIT#49]
After updating build commands that previously worked are failing now.
```
python unet.py --hf-hub-or-path "runwayml/stable-diffusion-v1-5" --width 512 512 --height 512 512 --batch-size 2 2 --clip-chunks 1 --model-name "v1_unet_512_512_2_2_c1_test" --work-dir "/home/primary/Documents/code/ML/AIT/modules"
```

```
2023-09-09 14:08:36,292 INFO <aitemplate.compiler.compiler> compiled the final .so file elapsed time: 0:03:22.475189
[14:08:36] model_container.cu:69: Device Runtime Version: 11080; Driver Version: 12010
[14:08:36] model_container.cu:83: Hardware accelerator device properties:
  Device:
     ASCII string identifying device: NVIDIA GeForce RTX 4090
     Major compute capability: 8
     Minor compute capability: 9
     UUID: GPU-3caeb811-53d4-7669-01dc-ca502ea01048
     Unique identifier for a group of devices on the same multi-GPU board: 0
     PCI bus ID of the device: 12
     PCI device ID of the device: 0
     PCI domain ID of the device: 0
  Memory limits:
     Constant memory available on device in bytes: 65536
     Global memory available on device in bytes: 25385107456
     Size of L2 cache in bytes: 75497472
     Shared memory available per block in bytes: 49152
     Shared memory available per multiprocessor in bytes: 102400
[14:08:36] model_container.cu:87: Init AITemplate Runtime with 1 concurrency
Traceback (most recent call last):
  File "/home/primary/Documents/code/ML/AIT/AITemplate/unet.py", line 141, in <module>
    compile_diffusers()
  File "/home/primary/mambaforge/envs/AITemplate/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/primary/mambaforge/envs/AITemplate/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/primary/mambaforge/envs/AITemplate/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/primary/mambaforge/envs/AITemplate/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/primary/Documents/code/ML/AIT/AITemplate/unet.py", line 104, in compile_diffusers
    compile_unet(
  File "/home/primary/Documents/code/ML/AIT/AITemplate/ait/compile/unet.py", line 305, in compile_unet
    vram = round(total_usage / 1024 / 1024)
                 ~~~~~~~~~~~~^~~~~~
TypeError: unsupported operand type(s) for /: 'Model' and 'int'
```

**Comment by M1kep** [comment]
The PR references https://github.com/hlky/AITemplate/releases/tag/0.3.33, but their account and repos seem to just be gone

**Comment by M1kep** [comment]
I luckily found a cached copy of the repo locally, though this issue is still present as the code is not available online.
