### ISSUE TITLE
Error Running Workflows

### ISSUE THREAD

**Issue by Piscabo** [FizzleDorf/AIT#52]
Of date none of the workflows runs through?
Prompt executed in 8.11 seconds
got prompt
INFO:comfyui-prompt-control:Resolving wildcards...
Prompt executor has been patched by Job Iterator!
3
Found 5 modules for windows v1 sm80 1 512 unet
Using 8763aa0cc5f5008bd0734664ae47e874c2641d9e8293e8bd84c8c8ca7f6084d0
!!! Exception during processing !!!
Traceback (most recent call last):
  File "A:\AI_Files\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "A:\AI_Files\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "A:\AI_Files\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "A:\AI_Files\ComfyUI\nodes.py", line 1236, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "A:\AI_Files\ComfyUI\custom_nodes\AIT\AITemplate\AITemplate.py", line 176, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "A:\AI_Files\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\hacky.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)
  File "A:\AI_Files\ComfyUI\custom_nodes\AIT\AITemplate\AITemplate.py", line 300, in sample
    sampler.model_denoise = comfy.samplers.CFGNoisePredictor(model_wrapper)
  File "A:\AI_Files\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 814, in __init__
    self.inner_model2.num_timesteps = model.num_timesteps
  File "A:\AI_Files\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'AITemplateModelWrapper' object has no attribute 'num_timesteps'

**Comment by Piscabo** [comment]
Even after the latest update, I'm still having this issue. Please just point out if I'm missing a model file or node to avoid this error... Thanks. 
''AttributeError: 'AITemplateModelWrapper' object has no attribute 'num_timesteps''

**Comment by masslevel** [comment]
I'm having the same error message. I think it happens because of [smZNodes](https://github.com/shiimizu/ComfyUI_smZNodes). It uses `num_timesteps` to implement the prompt editing capabilities which works great - just currently not with AIT.

[Prompt Control](https://github.com/asagi4/comfyui-prompt-control) is supposedly supporting AIT but I haven't tried it yet or analyzed how it's implemented.

**Comment by masslevel** [comment]
@Piscabo shiimizu updated smZNodes: https://github.com/shiimizu/ComfyUI_smZNodes/commit/f3d170f1974fc10f2d9dc9118f02c04fa8608f46 and my first tests show it's working perfectly with AIT now.
