### ISSUE TITLE
Cannot import

### ISSUE THREAD

**Issue by Piscabo** [FizzleDorf/AIT#66]
Are you not going to fix this issue? Would like to run my workflows, but this issue was reported 2weeks ago. And there is no fix yet?

Traceback (most recent call last):
  File "A:\AI_Files\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "A:\AI_Files\ComfyUI\custom_nodes\AIT\__init__.py", line 1, in <module>
    from .AITemplate.AITemplate import AITemplateLoader, AITemplateControlNetLoader, AITemplateVAEDecode, AITemplateVAEEncode, VAEEncodeForInpaint, AITemplateEmptyLatentImage, AITemplateLatentUpscale
  File "A:\AI_Files\ComfyUI\custom_nodes\AIT\AITemplate\AITemplate.py", line 414
    else:
    ^^^^
IndentationError: expected an indented block after 'if' statement on line 413

Cannot import A:\AI_Files\ComfyUI\custom_nodes\AIT module for custom nodes: expected an indented block after 'if' statement on line 413 (AITemplate.py, line 414)
![image](https://github.com/FizzleDorf/AIT/assets/123719842/2625eb8a-cf1f-4478-be82-37632e6714c7)

**Comment by Lancer1408** [comment]
I managed to fix that error, which seems to be a typo, however there lies a bigger issue on the node as the error trace shows incompatibility with fp16 or something not implemented to that mode
